### ISSUE TITLE
6950XT Counterfeit

### ISSUE THREAD

**Issue by DickDock** [scotthowson/ROG-STRIX-Z790-A-GAMING-WIFI-Intel-i9-13900k-RX-6800-XT-OpenCore-1.0.2#2]
I tried to copy 6950XT into 6900XT, but it didn’t work after configuring ACPI. Is there any special configuration required?

**Comment by scotthowson** [comment]
> I tried to copy 6950XT into 6900XT, but it didn’t work after configuring ACPI. Is there any special configuration required?

This is for a RX 6800 XT. 
In device properties have you changed the frambuffer patch?

This would be the ATY,Carswell framebuffer.
as well as spoofing device-id to '0x73BF'.

Here is some good resources for some guidance.
https://www.tonymacx86.com/threads/macos-12-3-update-causes-problems-for-5700-6800-6900-graphics-cards.319421/post-2312916

https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#native-amd-gpus

**Comment by DickDock** [comment]
OK, I'll give it a try, thank you very much.
