### ISSUE TITLE
After installation stuck on loop

### ISSUE THREAD

**Issue by iStorry** [scotthowson/ROG-STRIX-Z790-A-GAMING-WIFI-Intel-i9-13900k-RX-6800-XT-OpenCore-1.0.2#3]
Hey,

First of all thank you for EFI. I used your EFI to install macOS Sonoma 14.5, and the installation went smoothly. However, I'm encountering a boot loop issue right after installation (before reaching the macOS setup menu where you select language and Apple ID). I've tried booting with -v for verbose mode but haven't had any luck.

My specs are similar:

Asus ROG Strix Z790-A Gaming Wi-Fi D4
Intel Core i7-13700KF (13th Gen)
AMD Radeon RX 6600
Any suggestions on how to resolve this?

**Comment by scotthowson** [comment]
Try clearing NVRAM and keep trying, also updated to 1.0.2. Should be a lot of fixes for your system there :)
