### ISSUE TITLE
Thanks and a little advice

### ISSUE THREAD

**Issue by githubzijian** [scotthowson/ROG-STRIX-Z790-A-GAMING-WIFI-Intel-i9-13900k-RX-6800-XT-OpenCore-1.0.2#4]
Thank you very much, your EFI configuration files on my computer work very well (in addition to the computer sleep wake up, will be black screen for several seconds), but from your screenshot, I see you run computer R23 points is not high, I replaced the CPUFriendDataProvider kext drive, the computer performance is very much, You can try downloading, The link below: https://github.com/sqlsec/AsRock-Z690-Steel-Legend-i5-13600K/tree/main/EFI/OC/Kexts/CPUFriendDataProvider.kext

**Comment by githubzijian** [comment]
<img width="448" alt="截屏2024-09-05 20 36 47" src="https://github.com/user-attachments/assets/5d712636-0c03-43ea-a962-98a99f202308">

**Comment by scotthowson** [comment]
Thank you a ton! I haven't had the time to update everything but this will definitely be an addition! In a few weeks I will release all in full once everything is settled the way I believe it should be & you definitely pointed me in the correct direction! Again thank you for everything & will be testing it out on my end :)

**Comment by githubzijian** [comment]
> Thank you a ton! I haven't had the time to update everything but this will definitely be an addition! In a few weeks I will release all in full once everything is settled the way I believe it should be & you definitely pointed me in the correct direction! Again thank you for everything & will be testing it out on my end :)

Thank you for your long-term maintenance.

**Comment by githubzijian** [comment]
Thank you very much for your continuous maintenance and support, which makes it easy for us to use macOS!

- I try to the following, make computer wake up won't black screen for a while: [college https://dortania.github.io/OpenCore-Post-Install/usb/misc/keyboard.html#method-2-create-a-fa ke-acpi-device](https://dortania.github.io/OpenCore-Post-Install/usb/misc/keyboard.html#method-2-create-a-fake-acpi-device)

I recently found a problem that I hadn't noticed before :  I can't boot my win 11 through oc, I guess it has something to do with acpi file, but I don't know how to locate this problem.

**Comment by scotthowson** [comment]
The Windows 11 Boot menu is a custom menu tailored for my system. If you are trying to map it out you can follow this guide:
https://dortania.github.io/OpenCore-Multiboot/oc/linux.html#method-b-chainloading-a-efi-bootloader-grub2-systemd-boot

I also added HibernationFixup to the kexts in 1.0.2, try it and let me know :)
